server:
  port: 8080


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jobportal
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
    expiration-ms: 86400000 # 24 hours
    refresh-expiration-ms: 604800000 # 7 days
  sms:
    api-key: 4YjLFQI82ilyAZfSER1spGDTCK5a0UXMNOduHWzhB7gqx69t3VCRlnxwLIf3Kv9PFa67YAHJkONToi4j
    api-url: https://www.fast2sms.com/dev/bulkV2
