# Server configuration
server.port=8085

# Database Configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/sarkariresult_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Settings
jwt.secret=9a6563c197c202ba8c155d02cfbbde3d251177e08dbd8095d2c2068aaef1e0d3
# JWT Expiration time in milliseconds (e.g. 7 days)
jwt.expiration=604800000

# Scraper schedule (e.g. run every 2 hours)
# format: second, minute, hour, day of month, month, day(s) of week
scraper.cron=0 0 */2 * * *
